In [2]:
import os, sys
import numpy as np
import pandas as pd
from glob import glob 
from skimage.measure import regionprops
from skimage.io import imread, imsave
from os.path import abspath, dirname
sys.path.append("/Users/wangy6/Desktop/DATA/Codes/Python/n5_cut tiles/")
import n5_metadata_utils as n5mu
import concurrent.futures

In [3]:
lb=imread("/Volumes/multifish/Yuhan/LHA3/segmentation/segment/R3_label_affinity.tif")
roi = np.max(lb)
print(roi)

24201


In [4]:
lb.shape

(811, 1790, 1790)

In [26]:
    # get appropriate image data    
img='/Volumes/multifish/Yuhan/LHA3/stitch/R3_LHA3/export.n5/'
subpath='c2/s2'
#voxel size in µm (x, y, z)
vox= n5mu.read_voxel_spacing(img, subpath)
#image size in pixel (x, y, z)
grid=n5mu.read_voxel_grid(img, subpath)
size=grid*vox
print(vox)
print(grid)
print(size)

[0.92 0.92 0.84]
[1790 1790  811]
[1646.8  1646.8   681.24]


In [5]:
cell_ID=np.loadtxt("/Volumes/multifish/Yuhan/LHA3/segmentation/spot/vGluT2_vGAT/roi_ID.txt")

In [6]:
cell_ID.shape

(918,)

In [34]:
cell_ID

array([   38.,   101.,   121.,   134.,   155.,   199.,   204.,   223.,
         243.,   256.,   289.,   306.,   349.,   384.,   457.,   497.,
         505.,   523.,   544.,   561.,   565.,   573.,   591.,   608.,
         643.,   662.,   675.,   693.,   698.,   699.,   734.,   739.,
         747.,   773.,   785.,   868.,   873.,   886.,   903.,   912.,
         928.,   931.,   936.,   965.,   976.,   982.,  1009.,  1011.,
        1030.,  1039.,  1080.,  1081.,  1105.,  1139.,  1154.,  1179.,
        1218.,  1226.,  1240.,  1261.,  1284.,  1287.,  1297.,  1314.,
        1330.,  1351.,  1353.,  1355.,  1423.,  1435.,  1440.,  1451.,
        1462.,  1467.,  1488.,  1494.,  1528.,  1529.,  1536.,  1555.,
        1611.,  1613.,  1618.,  1632.,  1685.,  1686.,  1697.,  1728.,
        1737.,  1787.,  1800.,  1811.,  1841.,  1877.,  1895.,  1911.,
        1913.,  1914.,  1932.,  1936.,  1951.,  1955.,  1990.,  2027.,
        2053.,  2056.,  2089.,  2101.,  2122.,  2136.,  2138.,  2140.,
      

In [7]:
lb_stat = regionprops(lb)
a=[-1,-1,-1]
for i in cell_ID.astype(int):
    cen=np.asarray(lb_stat[i].centroid)
    a=np.vstack((a,cen))
    a=a[(a != -1).all(axis=1),:]
a.shape

(918, 3)

In [8]:
tl=np.array([0,0,0])
br=np.array([811,1790,1790])
a=np.vstack((a,tl))
a=np.vstack((a,br))
a.shape

(920, 3)

In [ ]:
a=np.vstack((a,loc))

In [9]:
%gui qt
from skimage import data
import napari
from skimage.io import imread, imsave
import numpy as np 

In [12]:
napari.gui_qt()
viewer = napari.Viewer(ndisplay=3)

In [18]:

x=a[:,2]                                                          
y=a[:,1]                                                          
z=a[:,0]
points1=np.stack((z,y,x), axis=-1)
viewer.add_points(points1, size=20, face_color='red',edge_color='red')

<Points layer 'Points' at 0x1fd0bcc0d0>

In [14]:
viewer.add_image(lb.astype('int16'))

<Image layer 'Image' at 0x1e98135090>

In [13]:
#Please note that the spot.txt file is in (x,y,z) format
#spot_dir='/Users/wangy6/Desktop/CEA265P_R1R12/'
#for spot in spot_dir:
    #tile=os.path.basename(f)
count=pd.read_csv('/Volumes/multifish/Yuhan/LHA3/segmentation/spot/processed/count_lipoRemove.csv',sep=',',header=None)

In [17]:
count.head

<bound method NDFrame.head of           0      1    2       3      4        5     6      7     8    9   \
0      ROI #  Meis2   Th  Gpr101  Gpr83  Slc17a6  BdnF  Calb2  Gal   Otp   
1          1     38   13       1     49      166    45    511     0    0   
2          2     63    7       0     15        9    12     36     0    0   
3          3     68   57       1      0      109    21    550     0    0   
4          4     48   41       0      0      113    84     90     0    0   
5          5     57    7      26      2       43    34     65     0    0   
6          6     66   19       0      0      563    33    131     0    0   
7          7     32   19      13      0      220    40    465     0    0   
8          8     17    3       7     10      137    31     25    12    0   
9          9    106   21       1      1       17    18     50     4    0   
10        10     23   34       0    228       60     2    137     0    0   
11        11    125   98       0     16       11    13    

In [117]:
np.savetxt('/Volumes/multifish/Yuhan/LHA3/segmentation/spot/R3_c3.txt', spot)

In [4]:
df = pd.DataFrame(np.empty([roi, 3]), columns=['roi','cetroid_position', 'area'],dtype=object)
lb_stat = regionprops(lb)
for i in range(0,roi): 
    df.loc[df.index[i], 'roi'] = i+1
    df.loc[df.index[i], 'cetroid_position'] = lb_stat[i].centroid
    df.loc[df.index[i], 'area'] = lb_stat[i].area
    #df.loc[df.index[j], 'shape'] = lb_stat[i].eccentricity
df.to_csv("/Volumes/multifish/Yuhan/LHA3/segmentation/segment/roi.csv", index=False)

In [5]:
lable=np.empty(roi,2)
for i in range(0,roi): 
    label(i,0) = i+1
    label(i,1) = lb_stat[i].centroid
    if 

pandas.core.series.Series

In [ ]:
df['cetroid_position']head

In [ ]:
lb=
ub
df['roi'][df['cetroid_position'] == 'Apples']

In [ ]:
spot=np.loadtxt("/Volumes/multifish/Yuhan/LHA3/segmentation/spot/processed/count_lipoRemove.csv")

In [107]:
def spot_count(spot, lb, vox):
    spot[:, :3] = spot[:, :3] / scale
    spot=spot[spot[:,0]<=grid[0]]
    spot=spot[spot[:,1]<=grid[1]]
    spot=spot[spot[:,2]<=grid[2]]
    spot=spot[spot[:,0]>=0]
    spot=spot[spot[:,1]>=0]
    spot=spot[spot[:,2]>=0]
    spot=spot[spot[:,3]>0]
    spot=np.round(spot).astype(int)
    num_spot=len(spot[:,])
    roi = np.max(lb)
    count=np.zeros((num_spot+1,1))
    output = list()
    for i in range(0,num_spot):
        idx=lb[spot[i,2],spot[i,1],spot[i,0]]
        if idx >0: 
            count[idx,1] = count[idx,1]+1
            out=spot[i,4]
            output.append(out)
    return count, output

In [74]:
spot[:, :3] = spot[:, :3] / scale

In [108]:
spot_count(spot, lb, vox)

IndexError: index 1 is out of bounds for axis 1 with size 1

In [101]:
spot=np.round(spot,decimals=0)

In [104]:
spot[11,2]

127

In [78]:
np.max(spot)

164417.0

In [60]:
spot[:, :3] = spot[:, :3] / scale

In [68]:
scale=np.array((4,4,2))

In [51]:
max(spot[:,2])

173.226365

In [20]:
int(spot[3,0])

296

In [53]:
spot=np.round(spot)

In [58]:
num_spot=len(spot[:,])
count=np.zeros((num_spot,1))

In [54]:
lb[int(spot[3,2]),int(spot[3,1]),int(spot[3,0])]

80

TypeError: type numpy.ndarray doesn't define __round__ method

In [76]:
def spot_count(i):
    count = np.count_nonzero(img_spot[lb==i+1])
    spot_id=np.unique(np.trim_zeros(img_spot[lb==i+1]))
    return i, count, spot_id

In [1]:
fx=sorted(glob("/Volumes/multifish/Yuhan/LHA3/segmentation/spot/R4_c0.txt"))
for f in fx:
    tile=os.path.basename(f)
    name=tile.split('.')[0]
    col1=name +'_' +'spot_count'
    col2=name +'_'+'spot_id'
    print(f)
    spot=np.loadtxt(f)
    #df_f = pd.DataFrame(np.empty([roi, 2]), columns=[col1, col2],dtype=object)
    
    img_spot=point2image(spot,lb,vox)
    print(img_spot.shape)

NameError: name 'glob' is not defined

In [74]:
output1 = list()
output2 = list()
output3 = list()
#multithread##
with concurrent.futures.ThreadPoolExecutor() as executor:
        for out1, out2, out3 in executor.map(spot_count, range(0, roi)):
            # put results into correct output list
            output1.append(out1)
            output2.append(out2)
            output3.append(out3)
output=np.dstack((output1, output2, output3))
count=pd.DataFrame(output[0,:], columns=['roi',col1,col2],dtype=object)

KeyboardInterrupt: 

In [52]:
spot_r3=np.loadtxt("/Volumes/multifish/Yuhan/LHA3/segmentation/spot_r3/R3_c0.txt", delimiter=',')

In [ ]:
np.count 

In [53]:
spot_r3.shape

(916909, 4)

In [118]:
spot[:, :3] = spot[:, :3] / vox
spot[:, 3]=np.where(spot[:, 3]<0,0, spot[:, 3])
spot=spot[spot[:,0]<=grid[0]]
spot=spot[spot[:,1]<=grid[1]]
spot=spot[spot[:,2]<=grid[2]]
num_spot=len(spot[:,])
img_spot=np.zeros(lb.shape, dtype='float32')

In [119]:
tile=os.path.basename(f)
name=tile.split('.')[0]
col1=name +'_' +'spot_count'
col2=name +'_'+'spot_id'
df_f = pd.DataFrame(np.empty([roi, 2]), columns=[col1, col2],dtype=object)

In [120]:
df_f.head()

R3_c0_spot_count R3_c0_spot_id
0     2.14256e-314  2.14256e-314
1     2.14256e-314  2.14256e-314
2     2.14256e-314  2.14256e-314
3     2.14256e-314  2.14256e-314
4     2.14256e-314  2.14256e-314

In [121]:
for n in range(0,num_spot):
    img_spot[int(spot[n,2]),int(spot[n,1]),int(spot[n,0])]=n+1

In [127]:
img_spot.shape

(811, 1790, 1790)

In [135]:
for sorted(i) in range(0,roi): 
    df_f.loc[df.index[i], col1] = np.count_nonzero(img_spot[lb==i+1])
    df_f.loc[df.index[i], col2] = np.unique(np.trim_zeros(img_spot[lb==i+1]))

SyntaxError: can't assign to function call (<ipython-input-135-8c687f92e341>, line 1)

In [132]:
df_f.head()

R3_c0_spot_count R3_c0_spot_id  col
0                1             1  1.0
1                5             5  5.0
2                0             0  NaN
3                0             0  NaN
4               13            13  NaN

In [66]:
max(spot[:,0])

2175.052636536908

In [69]:
np.count_nonzero(spot[spot[:,2]>=700])

328012

In [60]:
max(spot[:,1])

7138.778424336991

In [59]:
max(spot_r3[:,2])

391.85999223589897

In [55]:
lb.shape

(811, 1790, 1790)

In [103]:
spot[:, :3] = spot[:, :3] / vox

In [34]:
type(dim)

str

In [114]:
spot=spot[spot[:,1]<=grid[1]]

In [127]:


    ####covert to python (z,y,x) format####

In [6]:
?regionprops


In [145]:
#count=np.empty([roi,6])
#for i in range(0,roi): 
#    count[i,0]=i+1
#    count[i,1]=np.count_nonzero(img_spot[lb==i+1])
#.   count[i,2]=np.unique(np.trim_zeros(img_spot[lb==i+1]))
#    count[i,2]=lb_stat[i].area

In [149]:
df.to_csv("/Users/wangy6/Desktop/CEA265P_R1R12/count.csv", index=False)